### ISSUE TITLE
[BUG]Many errors when clicking on not active user.

### ISSUE THREAD

**Issue by mrEckendonk** [osTicket/osTicket-1.7#924]
When a user creates a ticket and I want to assign it to an agent it gives me a lot of errors. I receive them by email

Enviormnet
nginx
php 7.4.1

error 
```
[SELECT COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` IS NOT NULL AND A1.`ticket_id` = Z1.`ticket_id` AND A3.`object_type` = 'T' THEN A1.`ticket_id` END) AS `q15`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A3.`object_type` = 'T' THEN A1.`ticket_id` END) AS `q1`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A2.`state` = 'open' AND A1.`isanswered` = '0' AND A3.`object_type` = 'T' THEN A1.`ticket_id` END) AS `q2`, COUNT(DISTINCT CASE WHEN A1.`staff_id` IN (1) AND A2.`state` = 'open' AND A1.`staff_id` IN (1) AND A2.`state` = 'open' AND A1.`staff_id` IN (1) AND A3.`object_type` = 'T' THEN A1.`ticket_id` END) AS `q6`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2020-01-15 03:00:00' AND '2020-01-16 02:59:59' AND A3.`object_type` = 'T' THEN A1.`ticket_id` END) AS `q9`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A2.`state` = 'open' AND A1.`isanswered` = '1' AND A3.`object_type` = 'T' THEN A1.`ticket_id` END) AS `q3`, COUNT(DISTINCT CASE WHEN A1.`staff_id` IN (1) AND A2.`state` = 'open' AND A1.`staff_id` IN (1) AND A2.`state` = 'open' AND NOT A1.`staff_id` IN (1) AND A3.`object_type` = 'T' THEN A1.`ticket_id` END) AS `q7`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2020-01-14 03:00:00' AND '2020-01-15 02:59:59' AND A3.`object_type` = 'T' THEN A1.`ticket_id` END) AS `q10`, COUNT(DISTINCT CASE WHEN A2.`state` = 'open' AND A2.`state` = 'open' AND A1.`isoverdue` = '1' AND A3.`object_type` = 'T' THEN A1.`ticket_id` END) AS `q4`, COUNT(DISTINCT CASE WHEN A1.`staff_id` IN (1) AND A2.`state` = 'open' AND A3.`object_type` = 'T' THEN A1.`ticket_id` END) AS `q5`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2020-01-13 03:00:00' AND '2020-01-20 02:59:59' AND A3.`object_type` = 'T' THEN A1.`ticket_id` END) AS `q11`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A3.`object_type` = 'T' THEN A1.`ticket_id` END) AS `q8`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2020-01-01 03:00:00' AND '2020-02-01 02:59:59' AND A3.`object_type` = 'T' THEN A1.`ticket_id` END) AS `q12`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2020-01-01 03:00:00' AND '2020-04-01 02:59:59' AND A3.`object_type` = 'T' THEN A1.`ticket_id` END) AS `q13`, COUNT(DISTINCT CASE WHEN A2.`state` = 'closed' AND A2.`state` = 'closed' AND A1.`closed` BETWEEN '2020-01-01 03:00:00' AND '2021-01-01 02:59:59' AND A3.`object_type` = 'T' THEN A1.`ticket_id` END) AS `q14` FROM `ost_ticket` A1 JOIN `ost_ticket_status` A2 ON (A1.`status_id` = A2.`id`) LEFT JOIN `ost_thread` A3 ON (A3.`object_type` = 'T' AND A1.`ticket_id` = A3.`object_id`) LEFT JOIN `ost_thread_referral` A4 ON (A3.`id` = A4.`thread_id`) LEFT JOIN `ost_staff` A5 ON (A4.`object_type` = 'S' AND A4.`object_id` = A5.`staff_id`) LEFT JOIN `ost_thread` A6 ON (A1.`ticket_id` = A6.`object_id` AND A6.`object_type` = 'C') LEFT JOIN `ost_thread_referral` A7 ON (A6.`id` = A7.`thread_id`) LEFT JOIN `ost_staff` A8 ON (A7.`object_type` = 'S' AND A7.`object_id` = A8.`staff_id`) WHERE (A2.`state` = 'open' AND (A1.`staff_id` = 1 OR A5.`staff_id` = 1 OR A6.`object_type` = 'C' AND A8.`staff_id` = 1))]

Unknown column 'Z1.ticket_id' in 'field list'<br />
<br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(200): osTicket->logDBError()<br />
#1 (root)/include/class.orm.php(3459): db_query()<br />
#2 (root)/include/class.orm.php(3506): MySqlExecutor->execute()<br />
#3 (root)/include/class.orm.php(2093): MySqlExecutor->getArray()<br />
#4 (root)/include/class.orm.php(2043): HashArrayIterator->{closure}()<br />
#5 (root)/include/class.orm.php(2022): CallbackSimpleIterator->next()<br />
#6 (root)/include/class.orm.php(2031): CallbackSimpleIterator->rewind()<br />
#7 (root)/include/class.orm.php(1703): CallbackSimpleIterator->valid()<br />
#8 (root)/include/class.orm.php(1713): CachedResultSet->fillTo()<br />
#9 (root)/include/class.orm.php(1336): CachedResultSet->asArray()<br />
#10 (root)/include/class.orm.php(1359): QuerySet->all()<br />
#11 (root)/include/class.search.php(973): QuerySet->one()<br />
#12 (root)/include/class.search.php(905): SavedQueue::counts()<br />
#13 (root)/include/staff/templates/queue-tickets.tmpl.php(111): SavedQueue->getCount()<br />
#14 (root)/scp/tickets.php(539): require_once('/home/nginx/dom...')<br />
#15 {main}
```

**Comment by JediKev** [comment]
@Eckybrazzz 

Go to `ost_queue` table, copy the record with `id` of `15`, paste it here so we can do some research, and then delete the record in your database.

Also, you opened this issue in the wrong repo. You need to open all future issues here:
- https://github.com/osTicket/osTicket

Cheers
